name: Testing and building my app
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: getting my code first
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: installing node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '18.19.1'
      - name: installing dependencies
        run: npm install
      - name: testing app
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: getting my code first
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: installing node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '18.19.1'
      - name: installing dependencies
        run: npm install
      - name: start my app
        run: npm run build